name: bertopic
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.1
  - umap-learn=0.5.6
  - pip:
      - bertopic==0.16.4
      - hdbscan==0.8.38.post1
      - sentence-transformers==3.0.1
      - torch==2.3.1
      - mlflow==2.14.3
      - pyarrow==17.0.0
      - plotly==5.23.0
      - kaleido==0.2.1